services:
  db:
    image: mysql:latest
    ports:
      - "8000:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "songsnapdb"
      command: --default-authentication-plugin=mysql_native_password
  front-end:
    build: ./songsnap
    container_name: songsnap_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./songsnap:/app
      - /app/node_modules
  back-end:
    build: ./server
    restart: always
    container_name: songsnap_backend
    ports:
      - '9000:9000'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
